version: '3.8'
services:
  web:
    build: .
    command: gunicorn prod_django_project_aws.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on: []
